name: 'Codelyze - Coverage'
description: 'Github action to generate and upload coverage reports'
author: 'codelyze'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  token:
    description: 'Coverage upload token generated when project is created on codelyze.com'
    required: true
  file:
    description: 'Path to coverage file to use'
    required: true
  annotations:
    description: 'Show uncovered lines annotations'
    default: false
    required: false

outputs:
  coverage:
    description: 'Total coverage'

runs:
  using: node20
  main: dist/index.js
