name: 'Codelyze - Coverage'
description: 'Github action to generate and upload coverage reports'
author: 'codelyze'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  token:
    description:
      'Coverage upload token generated when project is created on codelyze.com'
    required: true
  gh-token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  path:
    description: 'Path to coverage file to use'
    required: true
  base-commit:
    description: 'Base commit SHA for diff calculation'
    required: true
  head-commit:
    description: 'Head commit SHA for diff calculation'
    required: true
  annotations:
    description: 'Show uncovered lines annotations'
    default: false
    required: false

outputs:
  percentage:
    description: 'Total percentage coverage'

runs:
  using: node20
  main: dist/index.js
